test-show: test-show.c show.c
	gcc -o show.test test-show.c

test-bits: test-bits.c bit-operator.c
	gcc -o test-bits.test test-bits.c

ex-test: ex-test.c
	gcc -o ex-test.test ex-test.c

clean:
	rm -f *.o *.test